INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Abdominal Aortic Aneurysm', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Acanthamoeba Infection', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('ACE (Adverse Childhood Experiences)', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Acinetobacter Infection', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Acquired Immune Deficiency Syndrome (AIDS)', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Adenovirus Infection', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Adenovirus Vaccination', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('ADHD [Attention Deficit/Hyperactivity Disorder]', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Adult Vaccinations', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Adverse Childhood Experiences (ACE)', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('AFib, AF (Atrial fibrillation)', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('African Trypanosomiasis', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Agricultural Safety', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('AHF (Alkhurma hemorrhagic fever)', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('AIDS (Acquired Immune Deficiency Syndrome)', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('AIDS (Acquired Immunodeficiency Syndrome)', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Alkhurma hemorrhagic fever (AHF)', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('ALS [Amyotrophic Lateral Sclerosis]', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Alzheimer''s Disease', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Amebiasis, Intestinal [Entamoeba histolytica infection]', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('American Indian and Alaska Native Vaccination', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('American Trypanosomiasis', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Amphibians and Fish, Infections from', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Amyotrophic Lateral Sclerosis', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Anaplasmosis, Human', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Ancylostoma duodenale Infection, Necator americanus Infection', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Angiostrongylus Infection', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Animal-Related Diseases', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Anisakiasis', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Anisakis Infection [Anisakiasis]', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Anthrax [Bacillus anthracis Infection]', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Anthrax Vaccination', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Antibiotic and Antimicrobial Resistance', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Antibiotic Use, Appropriate', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('see also Get Smart about Antibiotics Week', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Aortic Aneurysm', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Aortic Dissection', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arenavirus Infection', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthritis', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Childhood Arthritis', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Fibromyalgia', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Gout', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Osteoarthritis (OA)', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Rheumatoid Arthritis (RA)', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Ascariasis', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Ascaris Infection [Ascariasis]', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Aseptic Meningitis', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Aspergillosis', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Aspergillus Infection [Aspergillosis]', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Asthma', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Atrial fibrillation (AFib, AF)', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Attention Deficit/Hyperactivity Disorder', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Autism', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('see also Genetics and Genomics', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Avian Influenza', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic hip replacement', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic hip synovectomy', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic knee fusion', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic knee synovectomy', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic lateral release for patellar realignment', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic partial hip replacement', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic partial knee replacement', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic proximal realignment of the patella', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic revision hip surgery', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic revision knee surgery', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic shoulder fusion', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic shoulder replacement', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic shoulder synovectomy', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic thumb fusion', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic thumb joint replacement', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic toe fusion', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic toe joint replacement', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic total knee replacement', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic wrist fusion', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic wrist replacement', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic wrist synovectomy', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Artificial urinary sphincter surgery', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Atherectomy', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Atrial septal defect closure', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Atrioventricular canal repair', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Augmentation labiaplasty', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Autogenic bone marrow transplant', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Auxillary artery cannulation', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Awake craniotomy', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Awake extratemporal cortical resection', 1, 1, GETDATE())
INSERT INTO [dbo].[HealthConditionMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Axillary thoracotomy', 1, 1, GETDATE())
