INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Abdominal liposuction', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Abdominal myomectomy', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Abdominoperineal resection', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Above the knee amputation', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Acetabular augmentation wedge', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Adam''s apple reduction', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Adductor release', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Adjustable gastric banding', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Adrenalectomy', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Alarplasty', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Allogenic bone marrow transplant', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Alveolar cleft surgery', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Ambulatory phlebectomy', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Angiojet Rheolytic thrombectomy', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Ankle arthrocentesis', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Ankle fusion', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Ankle replacement', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Ankle synovectomy', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Anoplasty', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Anterior colporrhaphy', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Anterior cruciate ligament surgery', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Anterior exenteration', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Anterior neck dissection', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Anterolateral thoracotomy', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Aortic Aneurysm Repair', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Aortic valve repair surgery', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Aortic valve replacement surgery', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Aortobifemoral bypass', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Aortofemoral bypass', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Apicoectomy', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Appendectomy (Removal of Appendix)', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Argon laser trabeculoplasty', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arm amputation', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arm biopsy', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arm fasciotomy', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arm lift', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arm liposuction', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arm tendon transfer', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arm tumor excision', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arterial embolectomy', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arterial switch', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthrocentesis', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic ankle fusion', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic ankle replacement', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic ankle synovectomy', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic anterior cruciate ligament surgery', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic elbow fusion', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic elbow replacement', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic elbow synovectomy', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic finger fusion', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic finger joint replacement', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic finger synovectomy', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic foot fusion', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic foot joint replacement', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic hip fusion', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic hip replacement', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic hip synovectomy', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic knee fusion', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic knee synovectomy', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic lateral release for patellar realignment', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic partial hip replacement', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic partial knee replacement', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic proximal realignment of the patella', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic revision hip surgery', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic revision knee surgery', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic shoulder fusion', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic shoulder replacement', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic shoulder synovectomy', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic thumb fusion', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic thumb joint replacement', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic toe fusion', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic toe joint replacement', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic total knee replacement', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic wrist fusion', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic wrist replacement', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Arthroscopic wrist synovectomy', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Artificial urinary sphincter surgery', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Atherectomy', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Atrial septal defect closure', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Atrioventricular canal repair', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Augmentation labiaplasty', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Autogenic bone marrow transplant', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Auxillary artery cannulation', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Awake craniotomy', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Awake extratemporal cortical resection', 1, 1, GETDATE())
INSERT INTO [dbo].[SurgeryMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Axillary thoracotomy', 1, 1, GETDATE())
