USE [HealthCare] 
GO
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(1,'Tablet',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(1,'Buccal Tablet',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(1,'Sublingual Tablet',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(1,'Effervescent Tablet',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(1,'Chewable Tablet',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(1,'Capsule',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(1,'Lonzenge',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(1,'Pastilles',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(1,'Dental Cones',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(1,'Pills',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(1,'Granules',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(1,'Powder',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(2,'Oral Solution',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(2,'Oral Emulsion',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(2,'Oral Suspension',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(2,'Syrup',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(2,'Elixir',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(2,'Linctuses',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(2,'Oral Drops',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(2,'Gargles',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(2,'Mouthwashes',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(3,'Ointment',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(3,'Creams',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(3,'Gels (Jellies)',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(3,'Poultice',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(3,'Pastes',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(3,'Dusting Powders',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(3,'Liniments',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(3,'Lotions',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(3,'Collodion',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(3,'Paints',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(3,'Pressurized Dispensers',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(4,'Suppository',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(4,'Enema',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(5,'Pessary',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(6,'Intravenous',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(6,'Intramuscular',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(6,'Subcutaneous',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(6,'Intradermal',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(6,'Intracardiac',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(6,'Intraocular',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(6,'Intrathecal',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(6,'Intraarticular',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(7,'Inhaler',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(7,'Nebulizer',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(8,'Eye Drops',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(8,'Ophthalmic Ointment and Gel',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(9,'Ear Drop',1,1,GETDATE())
INSERT INTO [dbo].[DrugSubTypeMaster] ([DrugTypeId],[Description],[Active],[AddedBy],[AddedDate]) VALUES(10,'Nasal Drop',1,1,GETDATE())