INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Bahia Grass', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Barley Grass', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Bermuda Grass', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Brome, Smooth', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Canary Grass, Reed', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Corn, Cultivated', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Fescue, Meadow', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Foxtail, Meadow', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Johnson Grass', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Kentucky Bluegrass', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Oat, Cultivated', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Orchard Grass', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Red Top, Bentgrass', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Reed, Common', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Rye Grass', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Rye Grass, Perennial', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Rye Grass, Wild', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Salt Grass', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Sweet Vernal', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Timothy', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Velvet Grass', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Wheat, Cultivated', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Alder, Grey', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Ash, White', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Bayberry/Sweet Gale', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Beech, American', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Cedar, Mountain', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Cedar, Red', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Common Silver Birch', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Cottonwood', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Cypress, Bald', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Cypress, Italian', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Elm, American', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Elm, Cedar', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Eucalyptus', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Fir, Douglas', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Gum, Sweet', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Hackberry', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Hazelnut Tree', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Hickory, White', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Hop-Hornsbeam', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Japanese Cedar', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Lime Tree/Linden', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Maple/Box Elder', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Melaleuca', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Mesquite', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Mimosa/Acacia', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Mulberry, White', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Oak, Live/Virginia', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Oak, White', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Olive, Russian', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Olive Tree', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Palm, Queen', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Pecan, Hickory', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Pepper Tree', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Pine, Australian', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Pine, White', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Privet, Common', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Spruce', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Sycamore, Maple Leaf', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Walnut (Pollen)', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Willow', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Alfalfa', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Careless Weed', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Cocklebur', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Dandelion', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Dockweed, Yellow', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Fennel, Dog', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Goldenrod', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Kochia', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Lamb''s Quarters', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Lenscale', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Mugwort', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Nettle', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Pigweed, Common', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Plantain, English', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Ragweed, False', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Ragweed, Giant', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Ragweed, Short', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Ragweed, Western', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Rough Marshelder', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Sheep Sorrel', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Sunflower Pollen', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Thistle, Russian', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Wall Pellitory', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Wormwood', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Animal Mix (Cat, Cow, Dog, Horse)', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Budgerigar Droppings', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Budgerigar Feather', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Canary Feathers', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Cat Hair/Dander', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Chicken Feathers', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Cow Dander', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Deer Epithelium', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Dog Dander', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Duck Feathers', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Finch Feathers', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Gerbil Epithelium', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Goat Epithelium', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Goose Feathers', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Guinea Pig Epithelium', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Hamster Epithelium', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Horse Dander', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Mouse Epithelium', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Mouse Serum', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Mouse Urine', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Pigeon Feathers', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Rabbit Epithelium', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Rat Epithelium', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Rat Epithelium and Protein', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Rat Serum', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Rat Urine', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Sheep Epithelium', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Swine Epithelium', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Turkey Feathers', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Staphylococcus Enterotoxin A', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Tilletia tritici', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Alpha-Amylase', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Castor Bean', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Cotton Lint', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Ethylene Oxide', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Ficus', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Formaldehyde', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Isocyanate HDI', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Isocyanate MDI', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Isocyanate TDI', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Ispaghula', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Latex', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Oxeye Daisy', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Papain', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Phthalic Anhydride', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Seminal Fluid', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Silk', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Sunflower Seed', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Tobacco Dust', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Trimellitic Anhydride', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Adrenocorticotropic Hormone (ACTH)', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Amoxicilloyl', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Ampicilloyl', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Cefaclor', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Chymopapain', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Gelatin', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Insulin, Bovine', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Insulin, Human', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Insulin, Porcine', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Penicilloyl G', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Penicilloyl V', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Suxamethonium', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Acarus Mite', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Blomia tropicalis', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Dermatophagoides farinae', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Dermatophagoides pteronyssinus', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Euroglyphus maynei', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Glycyphagus domesticus', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Lepidoglyphus', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Tyrophagus', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Cockroach, American', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Cockroach, German', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Fire Ant (Invicta)', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Horse Fly', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Midge', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Moth', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Whole Body: Mosquito', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Bumblebee', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Honeybee', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Hornet, White Face', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Hornet, Yellow', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Wasp, Paper', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Yellow Jacket', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Acremonium kiliense', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Alternaria alternata', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Aspergillus fumigatus', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Aspergillus niger', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Aureobasidi pullulans', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Bipolaris', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Botrytis cinerea', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Candida albicans', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Chaetomium globosum', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Cladosporium herbarum', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Curvularia lunata', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Epicoccum purpur', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Fusarium proliferatum', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Mucor racemosus', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Penicillium chrysogenum', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Phoma betae', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Pityrosporum orbiculare', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Rhizopus nigricans', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Setomelanomma rostrata', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Stachybotrys atra', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Stemphylium herbarum', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Trichoderma viridae', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Trichophyton mentagro', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Trichophyton rubrum', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Ascaris', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Acacia Gum', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Allspice', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Almond', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Alpha-Lactalbumin', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Anchovy', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Aniseed', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Apple', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Apricot', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Asparagus', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Avocado', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Banana', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Barley', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Basil', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Bayleaf (Laurel)', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Beef', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Beta-Lactoglobulin', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Bing Cherry', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Black Pepper', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Blackberry', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Blueberry', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Boiled Milk', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Brazil Nut', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Broccoli', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Brussels Sprout', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Buckwheat', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Cabbage', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Carmine Red Dye', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Carob Bean', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Carrot', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Casein', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Cashew Nut', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Catfish', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Cauliflower', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Celery', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Cheese, Cheddar Type', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Cheese, Mold Type', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Chicken', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Chick Pea', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Chili Pepper', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Chocolate/Cacao', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Cinnamon', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Clam', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Cloves', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Coconut', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Codfish', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Coffee', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Coriander/Cilantro', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Corn', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Cottonseed', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Crab', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Cranberry', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Crayfish, Freshwater', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Cucumber', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Cumin', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Curry Powder', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Date', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Dill', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Egg White', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Egg, Whole', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Egg Yolk', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Eggplant', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Fennel, Fresh', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Fig', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Flounder', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Garlic', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Ginger', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Gluten', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Goat''s Milk', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Grape', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Grapefruit', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Green Bean', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Green Bell Pepper', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Green Pea', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Haddock', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Hake', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Halibut', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Hazelnut (Filbert)', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Herring', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Honey', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Hop (Food)', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Kidney Bean', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Kiwi Fruit', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Lamb', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Lemon', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Lentil', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Lettuce', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Lima Bean', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Lime', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Linseed', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Lobster', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Macadamia Nut', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Mackerel', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Malt', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Mango', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Melon', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Milk', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Millet', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Mint', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Mushroom', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Mussel', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Mustard', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Nutmeg', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Oat', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Olive, Black', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Onion', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Orange', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Oregano', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Ovalbumin', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Ovomucoid', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Oyster', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Papaya Food', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Paprika', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Parsley', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Peach', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Peanut', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Pear', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Pecan Nut', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Pine Nut, Pignoles', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Pineapple', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Pistachio Nut', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Plum', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Poppy Seed', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Pork', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Potato, White', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Pumpkin', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Rabbit Meat', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Raspberry', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Red Beet', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Red Snapper', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Rice', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Rye', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Sage, Salvia', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Salmon', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Sardine', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Scallop', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Sesame Seed', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Shrimp', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Sole', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Soybean', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Spinach', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Squid', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Strawberry', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Sweet Chestnut', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Sweet Potato', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Swordfish', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Tangerine', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Tea', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Thyme', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Tilapia', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Tomato', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Trout', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Tuna', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Turkey', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Vanilla', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Walleye Pike', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Walnut', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Watermelon', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Wheat', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Whey', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('White Bean', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Whitefish', 1, 1, GETDATE())
INSERT INTO [dbo].[AllergyMaster] ([Description],[Active],[AddedBy],[AddedDate]) VALUES ('Yeast', 1, 1, GETDATE())

