USE [HealthCare]
GO
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('ACDT','Australian Central Daylight Savings Time','UTC+10:30',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('ACST','Australian Central Standard Time','UTC+09:30',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('ACT','Acre Time','UTC−05',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('ACT','ASEAN Common Time','UTC+06:30 – UTC+09',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('ACWST','Australian Central Western Standard Time (unofficial)','UTC+08:45',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('ADT','Atlantic Daylight Time','UTC−03',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('AEDT','Australian Eastern Daylight Savings Time','UTC+11',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('AEST','Australian Eastern Standard Time','UTC+10',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('AFT','Afghanistan Time','UTC+04:30',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('AKDT','Alaska Daylight Time','UTC−08',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('AKST','Alaska Standard Time','UTC−09',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('AMST','Amazon Summer Time (Brazil)[1]','UTC−03',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('AMT','Amazon Time (Brazil)[2]','UTC−04',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('AMT','Armenia Time','UTC+04',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('ART','Argentina Time','UTC−03',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('AST','Arabia Standard Time','UTC+03',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('AST','Atlantic Standard Time','UTC−04',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('AWST','Australian Western Standard Time','UTC+08',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('AZOST','Azores Summer Time','UTC±00',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('AZOT','Azores Standard Time','UTC−01',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('AZT','Azerbaijan Time','UTC+04',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('BDT','Brunei Time','UTC+08',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('BIOT','British Indian Ocean Time','UTC+06',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('BIT','Baker Island Time','UTC−12',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('BOT','Bolivia Time','UTC−04',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('BRST','Brasília Summer Time','UTC−02',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('BRT','Brasilia Time','UTC−03',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('BST','Bangladesh Standard Time','UTC+06',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('BST','Bougainville Standard Time[3]','UTC+11',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('BST','British Summer Time (British Standard Time from Feb 1968 to Oct 1971)','UTC+01',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('BTT','Bhutan Time','UTC+06',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('CAT','Central Africa Time','UTC+02',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('CCT','Cocos Islands Time','UTC+06:30',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('CDT','Central Daylight Time (North America)','UTC−05',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('CDT','Cuba Daylight Time[4]','UTC−04',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('CEST','Central European Summer Time (Cf. HAEC)','UTC+02',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('CET','Central European Time','UTC+01',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('CHADT','Chatham Daylight Time','UTC+13:45',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('CHAST','Chatham Standard Time','UTC+12:45',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('CHOT','Choibalsan Standard Time','UTC+08',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('CHOST','Choibalsan Summer Time','UTC+09',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('CHST','Chamorro Standard Time','UTC+10',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('CHUT','Chuuk Time','UTC+10',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('CIST','Clipperton Island Standard Time','UTC−08',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('CIT','Central Indonesia Time','UTC+08',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('CKT','Cook Island Time','UTC−10',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('CLST','Chile Summer Time','UTC−03',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('CLT','Chile Standard Time','UTC−04',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('COST','Colombia Summer Time','UTC−04',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('COT','Colombia Time','UTC−05',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('CST','Central Standard Time (North America)','UTC−06',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('CST','China Standard Time','UTC+08',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('CST','Cuba Standard Time','UTC−05',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('CT','China Time','UTC+08',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('CVT','Cape Verde Time','UTC−01',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('CWST','Central Western Standard Time (Australia) unofficial','UTC+08:45',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('CXT','Christmas Island Time','UTC+07',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('DAVT','Davis Time','UTC+07',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('DDUT','Dumont d''Urville Time','UTC+10',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('DFT','AIX-specific equivalent of Central European Time[NB 1]','UTC+01',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('EASST','Easter Island Summer Time','UTC−05',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('EAST','Easter Island Standard Time','UTC−06',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('EAT','East Africa Time','UTC+03',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('ECT','Eastern Caribbean Time (does not recognise DST)','UTC−04',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('ECT','Ecuador Time','UTC−05',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('EDT','Eastern Daylight Time (North America)','UTC−04',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('EEST','Eastern European Summer Time','UTC+03',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('EET','Eastern European Time','UTC+02',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('EGST','Eastern Greenland Summer Time','UTC±00',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('EGT','Eastern Greenland Time','UTC−01',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('EIT','Eastern Indonesian Time','UTC+09',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('EST','Eastern Standard Time (North America)','UTC−05',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('FET','Further-eastern European Time','UTC+03',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('FJT','Fiji Time','UTC+12',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('FKST','Falkland Islands Summer Time','UTC−03',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('FKT','Falkland Islands Time','UTC−04',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('FNT','Fernando de Noronha Time','UTC−02',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('GALT','Galápagos Time','UTC−06',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('GAMT','Gambier Islands Time','UTC−09',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('GET','Georgia Standard Time','UTC+04',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('GFT','French Guiana Time','UTC−03',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('GILT','Gilbert Island Time','UTC+12',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('GIT','Gambier Island Time','UTC−09',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('GMT','Greenwich Mean Time','UTC±00',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('GST','South Georgia and the South Sandwich Islands Time','UTC−02',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('GST','Gulf Standard Time','UTC+04',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('GYT','Guyana Time','UTC−04',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('HDT','Hawaii–Aleutian Daylight Time','UTC−09',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('HAEC','Heure Avancée d''Europe Centrale French-language name for CEST','UTC+02',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('HST','Hawaii–Aleutian Standard Time','UTC−10',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('HKT','Hong Kong Time','UTC+08',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('HMT','Heard and McDonald Islands Time','UTC+05',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('HOVST','Khovd Summer Time','UTC+08',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('HOVT','Khovd Standard Time','UTC+07',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('ICT','Indochina Time','UTC+07',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('IDLW','International Day Line West time zone','UTC−12',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('IDT','Israel Daylight Time','UTC+03',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('IOT','Indian Ocean Time','UTC+03',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('IRDT','Iran Daylight Time','UTC+04:30',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('IRKT','Irkutsk Time','UTC+08',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('IRST','Iran Standard Time','UTC+03:30',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('IST','Indian Standard Time','UTC+05:30',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('IST','Irish Standard Time[5]','UTC+01',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('IST','Israel Standard Time','UTC+02',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('JST','Japan Standard Time','UTC+09',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('KALT','Kaliningrad Time','UTC+02',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('KGT','Kyrgyzstan Time','UTC+06',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('KOST','Kosrae Time','UTC+11',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('KRAT','Krasnoyarsk Time','UTC+07',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('KST','Korea Standard Time','UTC+09',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('LHST','Lord Howe Standard Time','UTC+10:30',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('LHST','Lord Howe Summer Time','UTC+11',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('LINT','Line Islands Time','UTC+14',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('MAGT','Magadan Time','UTC+12',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('MART','Marquesas Islands Time','UTC−09:30',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('MAWT','Mawson Station Time','UTC+05',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('MDT','Mountain Daylight Time (North America)','UTC−06',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('MET','Middle European Time Same zone as CET','UTC+01',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('MEST','Middle European Summer Time Same zone as CEST','UTC+02',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('MHT','Marshall Islands Time','UTC+12',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('MIST','Macquarie Island Station Time','UTC+11',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('MIT','Marquesas Islands Time','UTC−09:30',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('MMT','Myanmar Standard Time','UTC+06:30',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('MSK','Moscow Time','UTC+03',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('MST','Malaysia Standard Time','UTC+08',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('MST','Mountain Standard Time (North America)','UTC−07',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('MUT','Mauritius Time','UTC+04',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('MVT','Maldives Time','UTC+05',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('MYT','Malaysia Time','UTC+08',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('NCT','New Caledonia Time','UTC+11',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('NDT','Newfoundland Daylight Time','UTC−02:30',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('NFT','Norfolk Island Time','UTC+11',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('NPT','Nepal Time','UTC+05:45',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('NST','Newfoundland Standard Time','UTC−03:30',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('NT','Newfoundland Time','UTC−03:30',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('NUT','Niue Time','UTC−11',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('NZDT','New Zealand Daylight Time','UTC+13',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('NZST','New Zealand Standard Time','UTC+12',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('OMST','Omsk Time','UTC+06',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('ORAT','Oral Time','UTC+05',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('PDT','Pacific Daylight Time (North America)','UTC−07',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('PET','Peru Time','UTC−05',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('PETT','Kamchatka Time','UTC+12',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('PGT','Papua New Guinea Time','UTC+10',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('PHOT','Phoenix Island Time','UTC+13',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('PHT','Philippine Time','UTC+08',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('PKT','Pakistan Standard Time','UTC+05',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('PMDT','Saint Pierre and Miquelon Daylight Time','UTC−02',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('PMST','Saint Pierre and Miquelon Standard Time','UTC−03',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('PONT','Pohnpei Standard Time','UTC+11',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('PST','Pacific Standard Time (North America)','UTC−08',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('PST','Philippine Standard Time','UTC+08',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('PYST','Paraguay Summer Time[6]','UTC−03',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('PYT','Paraguay Time[7]','UTC−04',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('RET','Réunion Time','UTC+04',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('ROTT','Rothera Research Station Time','UTC−03',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('SAKT','Sakhalin Island Time','UTC+11',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('SAMT','Samara Time','UTC+04',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('SAST','South African Standard Time','UTC+02',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('SBT','Solomon Islands Time','UTC+11',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('SCT','Seychelles Time','UTC+04',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('SDT','Samoa Daylight Time','UTC−10',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('SGT','Singapore Time','UTC+08',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('SLST','Sri Lanka Standard Time','UTC+05:30',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('SRET','Srednekolymsk Time','UTC+11',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('SRT','Suriname Time','UTC−03',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('SST','Samoa Standard Time','UTC−11',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('SST','Singapore Standard Time','UTC+08',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('SYOT','Showa Station Time','UTC+03',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('TAHT','Tahiti Time','UTC−10',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('THA','Thailand Standard Time','UTC+07',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('TFT','Indian/Kerguelen','UTC+05',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('TJT','Tajikistan Time','UTC+05',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('TKT','Tokelau Time','UTC+13',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('TLT','Timor Leste Time','UTC+09',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('TMT','Turkmenistan Time','UTC+05',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('TRT','Turkey Time','UTC+03',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('TOT','Tonga Time','UTC+13',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('TVT','Tuvalu Time','UTC+12',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('ULAST','Ulaanbaatar Summer Time','UTC+09',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('ULAT','Ulaanbaatar Standard Time','UTC+08',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('UTC','Coordinated Universal Time','UTC±00',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('UYST','Uruguay Summer Time','UTC−02',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('UYT','Uruguay Standard Time','UTC−03',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('UZT','Uzbekistan Time','UTC+05',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('VET','Venezuelan Standard Time','UTC−04',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('VLAT','Vladivostok Time','UTC+10',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('VOLT','Volgograd Time','UTC+04',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('VOST','Vostok Station Time','UTC+06',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('VUT','Vanuatu Time','UTC+11',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('WAKT','Wake Island Time','UTC+12',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('WAST','West Africa Summer Time','UTC+02',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('WAT','West Africa Time','UTC+01',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('WEST','Western European Summer Time','UTC+01',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('WET','Western European Time','UTC±00',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('WIT','Western Indonesian Time','UTC+07',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('WST','Western Standard Time','UTC+08',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('YAKT','Yakutsk Time','UTC+09',1,1,GETDATE())
INSERT INTO [dbo].[TimezoneMaster] ([ShortForm],[Timezone],[Time],[Active],[AddedBy],[AddedDate]) VALUES ('YEKT','Yekaterinburg Time','UTC+05',1,1,GETDATE())


