USE [HealthCare]
GO
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Andhra Pradesh',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Arunachal Pradesh',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Assam',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Bihar',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Goa',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Gujarat',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Haryana',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Himachal Pradesh',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Jammu and Kashmir',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Karnataka',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Kerala',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Madhya Pradesh',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Maharashtra',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Manipur',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Meghalaya',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Mizoram',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Nagaland',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Orissa',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Punjab',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Rajasthan',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Sikkim',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Tamil Nadu',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Tripura',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Uttar Pradesh',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'West Bengal',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Chhattisgarh',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Uttarakhand',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Jharkhand',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Telangana',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Alabama',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Alaska',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Arizona',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Arkansas',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'California',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Colorado',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Connecticut',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Delaware',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Florida',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Georgia',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Hawaii',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Idaho',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Illinois',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Indiana',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Iowa',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Kansas',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Kentucky',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Louisiana',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Maine',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Maryland',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Massachusetts',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Michigan',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Minnesota',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Mississippi',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Missouri',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Montana',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Nebraska',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Nevada',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'New Hampshire',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'New Jersey',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'New Mexico',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'New York',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'North Carolina',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'North Dakota',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Ohio',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Oklahoma',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Oregon',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Pennsylvania',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Rhode Island',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'South Carolina',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'South Dakota',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Tennessee',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Texas',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Utah',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Vermont',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Virginia',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Washington',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'West Virginia',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Wisconsin',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (2,'Wyoming',1,1,GETDATE())
