USE [HealthCare]
GO
INSERT INTO [dbo].[BoardMaster] ([Board], [Description],[Active],[AddedBy],[AddedDate]) VALUES ('FAAEM','Fellow of the American Academy of Emergency Medicine',1,1,GETDATE())
INSERT INTO [dbo].[BoardMaster] ([Board], [Description],[Active],[AddedBy],[AddedDate]) VALUES ('FAAFP','Fellow of the American Academy of Family Physicians',1,1,GETDATE())
INSERT INTO [dbo].[BoardMaster] ([Board], [Description],[Active],[AddedBy],[AddedDate]) VALUES ('FACS','Fellow of the American Medical Association',1,1,GETDATE())
INSERT INTO [dbo].[BoardMaster] ([Board], [Description],[Active],[AddedBy],[AddedDate]) VALUES ('FFR','Fellow Faculty of Radiologists',1,1,GETDATE())
INSERT INTO [dbo].[BoardMaster] ([Board], [Description],[Active],[AddedBy],[AddedDate]) VALUES ('FRCPSC','Fellow of the Royal College of Physicians and Surgeons of Canada',1,1,GETDATE())
INSERT INTO [dbo].[BoardMaster] ([Board], [Description],[Active],[AddedBy],[AddedDate]) VALUES ('MRCOG','Member Royal College of Obstetricians and Gynecologists',1,1,GETDATE())
INSERT INTO [dbo].[BoardMaster] ([Board], [Description],[Active],[AddedBy],[AddedDate]) VALUES ('MRCS','Member Royal College of Surgeons',1,1,GETDATE())
INSERT INTO [dbo].[BoardMaster] ([Board], [Description],[Active],[AddedBy],[AddedDate]) VALUES ('Other Degrees and Associations','Other Degrees and Associations',1,1,GETDATE())
INSERT INTO [dbo].[BoardMaster] ([Board], [Description],[Active],[AddedBy],[AddedDate]) VALUES ('DD','Doctor of Divinity',1,1,GETDATE())
INSERT INTO [dbo].[BoardMaster] ([Board], [Description],[Active],[AddedBy],[AddedDate]) VALUES ('DEd or EdD','Doctor of Education',1,1,GETDATE())
INSERT INTO [dbo].[BoardMaster] ([Board], [Description],[Active],[AddedBy],[AddedDate]) VALUES ('DPA','Doctor of Public Administration',1,1,GETDATE())
INSERT INTO [dbo].[BoardMaster] ([Board], [Description],[Active],[AddedBy],[AddedDate]) VALUES ('DPH','Doctor of Public Health',1,1,GETDATE())
INSERT INTO [dbo].[BoardMaster] ([Board], [Description],[Active],[AddedBy],[AddedDate]) VALUES ('DPhil or PhD','Doctor of Philosophy',1,1,GETDATE())
INSERT INTO [dbo].[BoardMaster] ([Board], [Description],[Active],[AddedBy],[AddedDate]) VALUES ('FFPHM','Fellow Faculty of Public Health Medicine',1,1,GETDATE())
INSERT INTO [dbo].[BoardMaster] ([Board], [Description],[Active],[AddedBy],[AddedDate]) VALUES ('JD','Doctor of Jurisprudence',1,1,GETDATE())
INSERT INTO [dbo].[BoardMaster] ([Board], [Description],[Active],[AddedBy],[AddedDate]) VALUES ('PhD','Doctor of Philosophy',1,1,GETDATE())
INSERT INTO [dbo].[BoardMaster] ([Board], [Description],[Active],[AddedBy],[AddedDate]) VALUES ('PSYCH','Psychologist',1,1,GETDATE())
INSERT INTO [dbo].[BoardMaster] ([Board], [Description],[Active],[AddedBy],[AddedDate]) VALUES ('ScD','Doctor of Science',1,1,GETDATE())
INSERT INTO [dbo].[BoardMaster] ([Board], [Description],[Active],[AddedBy],[AddedDate]) VALUES ('SScD','Doctor of Social Science',1,1,GETDATE())
INSERT INTO [dbo].[BoardMaster] ([Board], [Description],[Active],[AddedBy],[AddedDate]) VALUES ('ThD','Doctor of Theology',1,1,GETDATE())
INSERT INTO [dbo].[BoardMaster] ([Board], [Description],[Active],[AddedBy],[AddedDate]) VALUES ('Other','Other',1,1,GETDATE())
