USE [HealthCare]
GO

INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Andhra Pradesh',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Arunachal Pradesh',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Assam',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Bihar',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Goa',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Gujarat',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Haryana',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Himachal Pradesh',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Jammu and Kashmir',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Karnataka',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Kerala',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Madhya Pradesh',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Maharashtra',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Manipur',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Meghalaya',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Mizoram',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Nagaland',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Orissa',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Punjab',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Rajasthan',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Sikkim',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Tamil Nadu',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Tripura',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Uttar Pradesh',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'West Bengal',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Chhattisgarh',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Uttarakhand',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Jharkhand',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Telangana',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Alabama',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Alaska',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Arizona',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Arkansas',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'California',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Colorado',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Connecticut',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Delaware',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Florida',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Georgia',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Hawaii',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Idaho',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Illinois',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Indiana',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Iowa',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Kansas',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Kentucky',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Louisiana',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Maine',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Maryland',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Massachusetts',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Michigan',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Minnesota',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Mississippi',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Missouri',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Montana',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Nebraska',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Nevada',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'New Hampshire',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'New Jersey',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'New Mexico',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'New York',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'North Carolina',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'North Dakota',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Ohio',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Oklahoma',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Oregon',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Pennsylvania',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Rhode Island',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'South Carolina',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'South Dakota',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Tennessee',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Texas',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Utah',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Vermont',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Virginia',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Washington',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'West Virginia',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Wisconsin',1,1,GETDATE())
INSERT INTO [dbo].[StateMaster] ([CountryId] ,[State] ,[Active] ,[AddedBy] ,[AddedDate] ) VALUES   (1,'Wyoming',1,1,GETDATE())


