USE [HealthCare]
GO

/****** Object:  StoredProcedure [dbo].[SP_CONSULTATION_PREVIOUSPREGNANCYDETAILS_LIST]    Script Date: 5/1/2018 5:27:45 PM ******/
DROP PROCEDURE [dbo].[SP_CONSULTATION_PREVIOUSPREGNANCYDETAILS_LIST]
GO

/****** Object:  StoredProcedure [dbo].[SP_CONSULTATION_PREVIOUSPREGNANCYDETAILS_LIST]    Script Date: 5/1/2018 5:27:45 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





CREATE PROCEDURE [dbo].[SP_CONSULTATION_PREVIOUSPREGNANCYDETAILS_LIST]
(	
	@CONSULTATION_ID BIGINT,
	@CONSULTATION_PREVIOUSPREGNANCYDETAILS_ID BIGINT = NULL,
	@CONSULTATION_CURRENTPREGNANCYDETAILS_ID BIGINT = NULL
)
AS

BEGIN

--EXEC [SP_CONSULTATION_PREVIOUSPREGNANCYDETAILS_LIST] 10018

SELECT CPPD.Id
	, CPPD.ConsultationId
	, CPPD.[CurrentPregnancyID]
	, CPPD.[NoofPregnancy]
	, CPPD.[ChildNo]
	, CPPD.[DeliveryYear]
	, CPPD.[DeliveryType]
	, CPPD.AddedBy
	, CPPD.AddedDate
	, CPPD.ModifiedBy
	, CPPD.ModifiedDate	
	FROM [ConsultationPreviousPregnancyDetails] CPPD
	INNER JOIN Consultation C ON CPPD.ConsultationId = C.Id
	WHERE C.Id = @CONSULTATION_ID
	AND (@CONSULTATION_CURRENTPREGNANCYDETAILS_ID IS NULL OR CPPD.CurrentPregnancyID = @CONSULTATION_CURRENTPREGNANCYDETAILS_ID)
	AND (@CONSULTATION_PREVIOUSPREGNANCYDETAILS_ID IS NULL OR CPPD.Id = @CONSULTATION_PREVIOUSPREGNANCYDETAILS_ID)
	ORDER BY CPPD.AddedDate DESC
END


GO


