USE [HealthCare]
GO

/****** Object:  StoredProcedure [dbo].[SP_GET_MENSTRUALSYMPTOMS_MASTER]    Script Date: 4/29/2018 4:27:08 PM ******/
DROP PROCEDURE [dbo].[SP_GET_MENSTRUALSYMPTOMS_MASTER]
GO

/****** Object:  StoredProcedure [dbo].[SP_GET_MENSTRUALSYMPTOMS_MASTER]    Script Date: 4/29/2018 4:27:08 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE PROCEDURE [dbo].[SP_GET_MENSTRUALSYMPTOMS_MASTER]
(
	@ACTIVE BIT = NULL,
	@DESCRIPTION NVARCHAR(100) =  NULL
)
AS

BEGIN

--EXEC [SP_GET_MENSTRUALSYMPTOMS_MASTER]
--EXEC [SP_GET_MENSTRUALSYMPTOMS_MASTER] 1, 'Acne'

	SELECT Id, [SymptomDescription]
	FROM MenstrualSymptomsMaster
	WHERE (@ACTIVE IS NULL OR [Active] = @ACTIVE)
	AND (@DESCRIPTION IS NULL OR [SymptomDescription] = @DESCRIPTION)  
	ORDER BY [Id]
END







GO


