USE [HealthCare]
GO

/****** Object:  StoredProcedure [dbo].[SP_CONSULTATION_SDDHABITS_LIST]    Script Date: 4/16/2018 12:18:40 AM ******/
DROP PROCEDURE [dbo].[SP_CONSULTATION_SDDHABITS_LIST]
GO

/****** Object:  StoredProcedure [dbo].[SP_CONSULTATION_SDDHABITS_LIST]    Script Date: 4/16/2018 12:18:40 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[SP_CONSULTATION_SDDHABITS_LIST]
(	
	@CONSULTATION_ID BIGINT,
	@CONSULTATION_SDDHABITS_ID BIGINT = NULL
)
AS

BEGIN

--EXEC [SP_CONSULTATION_ILLEGALDRUG_DETAILS_LIST] 10018

SELECT CSDDH.Id
	, CSDDH.ConsultationId
	, CSDDH.Consumedrugs
	, CSDDH.DoSmoke
	, CSDDH.EverSmoked
	, CSDDH.YearOfQuittingSmoking
	, CSDDH.SmokingFreq
	, CSDDH.AddedBy
	, CSDDH.AddedDate
	, CSDDH.ModifiedBy
	, CSDDH.ModifiedDate	
	FROM [ConsultationSDDHabits] CSDDH
	INNER JOIN Consultation C ON CSDDH.ConsultationId = C.Id
	WHERE C.Id = @CONSULTATION_ID
	AND (@CONSULTATION_SDDHABITS_ID IS NULL OR CSDDH.Id =@CONSULTATION_SDDHABITS_ID)
	ORDER BY CSDDH.AddedDate DESC
END






GO


