USE [HealthCare]
GO

/****** Object:  StoredProcedure [dbo].[SP_GET_DRUG_TYPE_MASTER]    Script Date: 4/18/2018 9:29:33 AM ******/
DROP PROCEDURE [dbo].[SP_GET_DRUG_TYPE_MASTER]
GO

/****** Object:  StoredProcedure [dbo].[SP_GET_DRUG_TYPE_MASTER]    Script Date: 4/18/2018 9:29:33 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_GET_DRUG_TYPE_MASTER]
(
	@ACTIVE BIT = NULL,
	@DESCRIPTION NVARCHAR(100) =  NULL,
	@SEARCH_TERM NVARCHAR(100) =  NULL
)
AS

BEGIN

--EXEC [SP_GET_DRUG_TYPE_MASTER]
--EXEC [SP_GET_DRUG_TYPE_MASTER] 1, 'Topical'
--EXEC [SP_GET_DRUG_TYPE_MASTER] 1, null, 'T'

	SELECT Id, [Description]
	FROM [DrugTypeMaster]
	WHERE (@ACTIVE IS NULL OR [Active] = @ACTIVE)
	AND (@DESCRIPTION IS NULL OR [Description] = @DESCRIPTION) 
	AND (@SEARCH_TERM IS NULL OR [Description] like '%' + @SEARCH_TERM + '%') 
	ORDER BY [Description]
END








GO


