USE [HealthCare]
GO

/****** Object:  StoredProcedure [dbo].[SP_GET_HEALTH_CONDITION_MASTER]    Script Date: 4/9/2018 9:31:42 PM ******/
DROP PROCEDURE [dbo].[SP_GET_HEALTH_CONDITION_MASTER]
GO

/****** Object:  StoredProcedure [dbo].[SP_GET_HEALTH_CONDITION_MASTER]    Script Date: 4/9/2018 9:31:42 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SP_GET_HEALTH_CONDITION_MASTER]
(
	@ACTIVE BIT = NULL,
	@DESCRIPTION NVARCHAR(100) =  NULL,
	@SEARCH_TERM NVARCHAR(100) =  NULL
)
AS

BEGIN

--EXEC [SP_GET_HEALTH_CONDITION_MASTER]
--EXEC [SP_GET_HEALTH_CONDITION_MASTER] 1, 'Abdominal Aortic Aneurysm'
--EXEC [SP_GET_HEALTH_CONDITION_MASTER] 1, null, 'Abdo'

	SELECT Id, [Description]
	FROM [HealthConditionMaster]
	WHERE (@ACTIVE IS NULL OR [Active] = @ACTIVE)
	AND (@DESCRIPTION IS NULL OR [Description] = @DESCRIPTION) 
	AND (@SEARCH_TERM IS NULL OR [Description] like '%' + @SEARCH_TERM + '%') 
	ORDER BY [Description]
END





GO


