USE [HealthCare]
GO

/****** Object:  StoredProcedure [dbo].[SP_GET_RELATIONSHIPS]    Script Date: 4/15/2018 11:46:27 AM ******/
DROP PROCEDURE [dbo].[SP_GET_RELATIONSHIPS]
GO

/****** Object:  StoredProcedure [dbo].[SP_GET_RELATIONSHIPS]    Script Date: 4/15/2018 11:46:27 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO






CREATE PROCEDURE [dbo].[SP_GET_RELATIONSHIPS]
(	
	@RELATIONSHIP_NAME NVARCHAR(200) = NULL,	
	@EXCLUDE_SELF BIT = 0,
	@ACTIVE BIT = NULL
)
AS

BEGIN

--EXEC [SP_GET_RELATIONSHIPS] 
--EXEC [SP_GET_RELATIONSHIPS] 'Owner',0

/*BLOCK TO GET THE RELATIONSHIP ID OF "SELF"*/
DECLARE @SELF_ID AS BIGINT 
	SELECT @SELF_ID = ID FROM RelationshipMaster
		WHERE [Description] = 'Self'

	SELECT *
	FROM [RelationshipMaster]
	WHERE (@RELATIONSHIP_NAME IS NULL OR [Description] = @RELATIONSHIP_NAME)
	AND (@ACTIVE IS NULL OR [Active] = @ACTIVE) 
	AND (@EXCLUDE_SELF = 0  OR Id <> @SELF_ID)
END













GO


