USE [HealthCare]
GO

/****** Object:  StoredProcedure [dbo].[SP_GET_DRUG_SUB_TYPE_MASTER]    Script Date: 4/26/2018 12:33:34 PM ******/
DROP PROCEDURE [dbo].[SP_GET_DRUG_SUB_TYPE_MASTER]
GO

/****** Object:  StoredProcedure [dbo].[SP_GET_DRUG_SUB_TYPE_MASTER]    Script Date: 4/26/2018 12:33:34 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[SP_GET_DRUG_SUB_TYPE_MASTER]
(
	@DRUG_TYPE_ID INT,
	@ACTIVE BIT = NULL,
	@DESCRIPTION NVARCHAR(100) =  NULL,
	@SEARCH_TERM NVARCHAR(100) =  NULL
)
AS

BEGIN

--EXEC [SP_GET_DRUG_SUB_TYPE_MASTER] 1, 1
--EXEC [SP_GET_DRUG_SUB_TYPE_MASTER] 1, 1, 'Tablet'
--EXEC [SP_GET_DRUG_SUB_TYPE_MASTER] 1, 1, null, 'Tablet'

	SELECT Id, @DRUG_TYPE_ID AS DrugTypeId, [Description]
	FROM [DrugSubTypeMaster]
	WHERE DrugTypeId = @DRUG_TYPE_ID
	AND (@ACTIVE IS NULL OR [Active] = @ACTIVE)
	AND (@DESCRIPTION IS NULL OR [Description] = @DESCRIPTION) 
	AND (@SEARCH_TERM IS NULL OR [Description] like '%' + @SEARCH_TERM + '%') 
	ORDER BY [Description]
END









GO


