USE [HealthCare]
GO

/****** Object:  StoredProcedure [dbo].[SP_GET_DRUG_BRAND_MASTER]    Script Date: 4/26/2018 11:12:47 AM ******/
DROP PROCEDURE [dbo].[SP_GET_DRUG_BRAND_MASTER]
GO

/****** Object:  StoredProcedure [dbo].[SP_GET_DRUG_BRAND_MASTER]    Script Date: 4/26/2018 11:12:47 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SP_GET_DRUG_BRAND_MASTER]
(
	@ACTIVE BIT = NULL,
	@DESCRIPTION NVARCHAR(100) =  NULL,
	@SEARCH_TERM NVARCHAR(100) =  NULL
)
AS

BEGIN

--EXEC [SP_GET_DRUG_BRAND_MASTER]
--EXEC [SP_GET_DRUG_BRAND_MASTER] 1, 'Others'
--EXEC [SP_GET_DRUG_BRAND_MASTER] 1, null, '1'

	SELECT Id, [Description]
	FROM [DrugBrandMaster]
	WHERE (@ACTIVE IS NULL OR [Active] = @ACTIVE)
	AND (@DESCRIPTION IS NULL OR [Description] = @DESCRIPTION) 
	AND (@SEARCH_TERM IS NULL OR [Description] like '%' + @SEARCH_TERM + '%') 
	ORDER BY [Description]
END








GO


